name: generate README with a random meme

on:
  schedule:
    - cron: '*/5 * * * *'
jobs: 
  gen_readme_with_meme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./generateMeme
        