name: generate README with a random meme

on:
  schedule:
    - cron: '*/5 * * * *'
jobs: 
  gen_readme_with_meme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: node redditDankMeme.js
